# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lrzbl/Desktop/FPGA-FinalProje/ps2-control-led/ps2-control-led.cache/wt [current_project]
set_property parent.project_path C:/Users/lrzbl/Desktop/FPGA-FinalProje/ps2-control-led/ps2-control-led.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/lrzbl/Desktop/FPGA-FinalProje/ps2-control-led/ps2-control-led.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/lrzbl/Desktop/FPGA-FinalProje/MouseBaseCodes/etonw/ps2_tx.vhd
  C:/Users/lrzbl/Desktop/FPGA-FinalProje/MouseBaseCodes/etonw/ps2_rx.vhd
  C:/Users/lrzbl/Desktop/FPGA-FinalProje/MouseBaseCodes/etonw/ps2_rxtx.vhd
  C:/Users/lrzbl/Desktop/FPGA-FinalProje/MouseBaseCodes/etonw/mouse.vhd
  C:/Users/lrzbl/Desktop/FPGA-FinalProje/MouseBaseCodes/etonw/mouse_led.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/lrzbl/Desktop/FPGA5HAFTA/Chu Codes/constraint/Nexys4_DDR_chu.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lrzbl/Desktop/FPGA5HAFTA/Chu Codes/constraint/Nexys4_DDR_chu.xdc}}]


synth_design -top mouse_led -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mouse_led.dcp

catch { report_utilization -file mouse_led_utilization_synth.rpt -pb mouse_led_utilization_synth.pb }
