# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/lrzbl/Desktop/FPGA5HAFTA/Chu Codes/constraint/Nexys4_DDR_chu.xdc

# Block Designs: bd/TAB/TAB.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB || ORIG_REF_NAME==TAB}]

# IP: bd/TAB/ip/TAB_microblaze_0_0/TAB_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_microblaze_0_0 || ORIG_REF_NAME==TAB_microblaze_0_0}]

# IP: bd/TAB/ip/TAB_mdm_1_0/TAB_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_mdm_1_0 || ORIG_REF_NAME==TAB_mdm_1_0}]

# IP: bd/TAB/ip/TAB_clk_wiz_1_0/TAB_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_clk_wiz_1_0 || ORIG_REF_NAME==TAB_clk_wiz_1_0}]

# IP: bd/TAB/ip/TAB_rst_clk_wiz_1_100M_0/TAB_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==TAB_rst_clk_wiz_1_100M_0}]

# IP: bd/TAB/ip/TAB_axi_gpio_0_0/TAB_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_axi_gpio_0_0 || ORIG_REF_NAME==TAB_axi_gpio_0_0}]

# IP: bd/TAB/ip/TAB_microblaze_0_axi_periph_0/TAB_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_microblaze_0_axi_periph_0 || ORIG_REF_NAME==TAB_microblaze_0_axi_periph_0}]

# IP: bd/TAB/ip/TAB_xbar_0/TAB_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_xbar_0 || ORIG_REF_NAME==TAB_xbar_0}]

# IP: bd/TAB/ip/TAB_auto_pc_1/TAB_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_auto_pc_1 || ORIG_REF_NAME==TAB_auto_pc_1}]

# IP: bd/TAB/ip/TAB_auto_pc_0/TAB_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_auto_pc_0 || ORIG_REF_NAME==TAB_auto_pc_0}]

# IP: bd/TAB/ip/TAB_dlmb_v10_0/TAB_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_dlmb_v10_0 || ORIG_REF_NAME==TAB_dlmb_v10_0}]

# IP: bd/TAB/ip/TAB_ilmb_v10_0/TAB_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_ilmb_v10_0 || ORIG_REF_NAME==TAB_ilmb_v10_0}]

# IP: bd/TAB/ip/TAB_dlmb_bram_if_cntlr_0/TAB_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==TAB_dlmb_bram_if_cntlr_0}]

# IP: bd/TAB/ip/TAB_ilmb_bram_if_cntlr_0/TAB_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==TAB_ilmb_bram_if_cntlr_0}]

# IP: bd/TAB/ip/TAB_lmb_bram_0/TAB_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TAB_lmb_bram_0 || ORIG_REF_NAME==TAB_lmb_bram_0}]

# XDC: bd/TAB/TAB_ooc.xdc
