# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lrzbl/Desktop/fpga2.odev/TAB/TAB.srcs/sources_1/bd/TAB/ip/TAB_auto_pc_1/TAB_auto_pc_1.xci
# IP: The module: 'TAB_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lrzbl/Desktop/fpga2.odev/TAB/TAB.srcs/sources_1/bd/TAB/ip/TAB_auto_pc_1/TAB_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TAB_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/lrzbl/Desktop/fpga2.odev/TAB/TAB.srcs/sources_1/bd/TAB/ip/TAB_auto_pc_1/TAB_auto_pc_1.xci
# IP: The module: 'TAB_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lrzbl/Desktop/fpga2.odev/TAB/TAB.srcs/sources_1/bd/TAB/ip/TAB_auto_pc_1/TAB_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TAB_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
